import React from "react";
import "./homePage.scss";
import Hero from "./sections/hero/hero";
import Section2 from "./sections/section2/section2";
import Section3 from "./sections/section3/section3";
import Section4 from "./sections/section4/section4";
import Section5 from "./sections/section5/section5";
import Section6 from "./sections/section6/section6";
import Section7 from "./sections/section7/section7";
import Section8 from "./sections/section8/section8";

export const metadata = {
  title: "Gamechaner",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <main>
      <Hero />
      <Section2 />
      <Section3 />
      <Section4 />
      <Section5 />
      <Section6 />
      <Section7 />
      <Section8/>
    </main>
  );
}